#端口号
server:
  port: 8080
#连接数据库的四要素
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store_db?unicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 338090
    type: com.alibaba.druid.pool.DruidDataSource #设置Druid的数据源类型
druid:
  max-wait: 3000 #最大等待事件
  initial-size: 2 #初始时的连接数

  # 日志配置
logging:
  level:
    root: info                    # 全局日志级别
    com.cdu: debug
    org.mybatis: debug
    com.cdu.mapper: debug

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.cdu.pojo.entity

avatar:
  save:
    path: ${user.home}/mallApp/avatar/